name: Store Traffic Analytics

# NOTE: This workflow requires admin permissions on the repository to access traffic data.
# The GITHUB_TOKEN in Actions does not have access to traffic API for public repositories.
#
# To enable this workflow, create a Fine-Grained Personal Access Token:
#
# 1. Go to: https://github.com/settings/personal-access-tokens/new
# 2. Configure the token:
#    - Token name: "AAVE Traffic Analytics Read-Only"
#    - Expiration: 90 days (recommended)
#    - Repository access: Select "th3nolo/aave-v3-data" only
# 3. Set ONLY these permissions:
#    - Contents: Read and write (to commit traffic data)
#    - Administration: Read (to access traffic API)
#    - Actions: NOT NEEDED (workflow runs automatically)
# 4. Generate and copy the token
# 5. Add as repository secret:
#    - Go to: Settings → Secrets and variables → Actions
#    - Name: TRAFFIC_TOKEN
#    - Value: Your fine-grained token
#
# Fine-grained tokens are more secure than classic tokens as they provide
# minimal required permissions and are scoped to a single repository.
#
# The workflow will use TRAFFIC_TOKEN if available, otherwise fallback to GITHUB_TOKEN

on:
  schedule:
    # Run daily at 1:00 UTC (after data update)
    - cron: '0 1 * * *'
  workflow_dispatch: {}

permissions:
  contents: write
  actions: read

jobs:
  traffic:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        pip install requests pandas
        
    - name: Create traffic analytics script
      run: |
        cat > traffic_analytics.py << 'SCRIPT'
        import requests
        import json
        import os
        from datetime import datetime
        import pandas as pd
        
        # Get the token - prefer TRAFFIC_TOKEN, fallback to FALLBACK_TOKEN
        token = os.environ.get("GITHUB_TOKEN") or os.environ.get("FALLBACK_TOKEN")
        
        if not token:
            print("Error: No GitHub token available")
            exit(1)
        
        # GitHub API headers
        headers = {
            'Authorization': f'token {token}',
            'Accept': 'application/vnd.github.v3+json'
        }
        
        # SECURITY: Never print the full token
        print(f"Using token: {token[:4]}...{token[-4:]}")
        
        # Repository info
        repo = os.environ.get('GITHUB_REPOSITORY', 'th3nolo/aave-v3-data')
        
        # Verify we're in the right repository (security check)
        if repo != 'th3nolo/aave-v3-data':
            print(f"Error: Unexpected repository: {repo}")
            exit(1)
        
        # Fetch views
        views_url = f'https://api.github.com/repos/{repo}/traffic/views'
        views_response = requests.get(views_url, headers=headers)
        if views_response.status_code == 403:
            print("Warning: Cannot access traffic data. This requires admin permissions on the repository.")
            print("Traffic data collection is only available to repository administrators.")
            print("Skipping traffic data collection.")
            exit(0)
        views_data = views_response.json() if views_response.status_code == 200 else {}
        
        # Fetch clones
        clones_url = f'https://api.github.com/repos/{repo}/traffic/clones'
        clones_response = requests.get(clones_url, headers=headers)
        clones_data = clones_response.json() if clones_response.status_code == 200 else {}
        
        # Fetch referrers
        referrers_url = f'https://api.github.com/repos/{repo}/traffic/popular/referrers'
        referrers_response = requests.get(referrers_url, headers=headers)
        referrers_data = referrers_response.json() if referrers_response.status_code == 200 else []
        
        # Fetch popular paths
        paths_url = f'https://api.github.com/repos/{repo}/traffic/popular/paths'
        paths_response = requests.get(paths_url, headers=headers)
        paths_data = paths_response.json() if paths_response.status_code == 200 else []
        
        # Load existing data
        traffic_file = 'traffic_data/traffic_history.json'
        if os.path.exists(traffic_file):
            with open(traffic_file, 'r') as f:
                history = json.load(f)
        else:
            history = {'views': [], 'clones': [], 'referrers': [], 'paths': []}
        
        # Add timestamp
        timestamp = datetime.utcnow().isoformat()
        
        # Store data
        if views_data:
            history['views'].append({
                'timestamp': timestamp,
                'count': views_data.get('count', 0),
                'uniques': views_data.get('uniques', 0),
                'views': views_data.get('views', [])
            })
        
        if clones_data:
            history['clones'].append({
                'timestamp': timestamp,
                'count': clones_data.get('count', 0),
                'uniques': clones_data.get('uniques', 0),
                'clones': clones_data.get('clones', [])
            })
        
        if referrers_data:
            history['referrers'].append({
                'timestamp': timestamp,
                'data': referrers_data
            })
        
        if paths_data:
            history['paths'].append({
                'timestamp': timestamp,
                'data': paths_data
            })
        
        # Create directory if needed
        os.makedirs('traffic_data', exist_ok=True)
        
        # Save updated history
        with open(traffic_file, 'w') as f:
            json.dump(history, f, indent=2)
        
        # Generate summary badge data
        total_views = sum(item['count'] for item in history['views'])
        total_clones = sum(item['count'] for item in history['clones'])
        
        badge_data = {
            'schemaVersion': 1,
            'label': 'Total Views',
            'message': str(total_views),
            'color': 'brightgreen'
        }
        
        with open('traffic_data/views_badge.json', 'w') as f:
            json.dump(badge_data, f)
        
        # Generate traffic report
        views_count = views_data.get('count', 0)
        views_uniques = views_data.get('uniques', 0)
        clones_count = clones_data.get('count', 0)
        clones_uniques = clones_data.get('uniques', 0)
        
        report = f"""# Traffic Analytics Report

Generated: {timestamp}

## Recent Activity (14 days)

- **Views**: {views_count} total, {views_uniques} unique
- **Clones**: {clones_count} total, {clones_uniques} unique

## Top Referrers

| Source | Views | Unique Visitors |
|--------|-------|-----------------|
"""
        
        for ref in referrers_data[:10]:
            report += f"| {ref.get('referrer', 'N/A')} | {ref.get('count', 0)} | {ref.get('uniques', 0)} |\n"
        
        report += "\n## Popular Content\n\n"
        report += "| Path | Views | Unique Visitors |\n"
        report += "|------|-------|------------------|\n"
        
        for path in paths_data[:10]:
            report += f"| {path.get('path', 'N/A')} | {path.get('count', 0)} | {path.get('uniques', 0)} |\n"
        
        with open('traffic_data/TRAFFIC_REPORT.md', 'w') as f:
            f.write(report)
        
        print(f"Traffic data updated: {total_views} total views, {total_clones} total clones")
        SCRIPT
        
    - name: Run traffic analytics
      env:
        # Use TRAFFIC_TOKEN if available, fallback to GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.TRAFFIC_TOKEN }}
        FALLBACK_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python traffic_analytics.py
        
    - name: Commit traffic data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add traffic_data/
        git diff --staged --quiet || git commit -m "Update traffic analytics - $(date -u '+%Y-%m-%d')"
        git push